# Generated by Django 3.0.6 on 2020-06-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
