# Generated by Django 3.0.6 on 2020-06-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_products_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/images')),
                ('category', models.CharField(choices=[('LR', 'Rayonnages lourds'), ('MI', 'Rayonnages mi-lourd'), ('LG', 'Rayonnages léger'), ('PR', 'Protection'), ('AC', 'Accessoires')], max_length=2)),
                ('active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
